stages:
  data_loading:
    cmd: python src/data/data_loading.py
    deps:
    - src/data/data_loading.py
    outs:
    - Data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - Data/raw/train.csv
    - Data/raw/test.csv
    - src/data/data_preprocessing.py
    outs:
    - Data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - Data/processed/X_train_scaled.npy
    - Data/processed/y_train.npy
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    - model_building.class_weight
    outs:
    - models/rf_model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - models/rf_model.pkl
      - Data/processed/X_train_scaled.npy
      - Data/processed/y_train.npy
      - Data/processed/X_valid_scaled.npy
      - Data/processed/y_valid.npy
      - Data/processed/X_test_scaled.npy
      - Data/processed/y_test.npy
      - src/model/model_evaluation.py
    outs:
      - log/experiment_info.json
      - log/validation_confusion_matrix.png
      - log/test_confusion_matrix.png
      - log/model_evaluation.log

  register_model:
    cmd: python src/model/register_model.py
    deps:
      - log/experiment_info.json
      - src/model/register_model.py
    outs:
      - log/model_registration.log

